CREATE TABLE [dbo].[ProductQualityChemical]
(
	[ProductQualityChemicalId] INT NOT NULL PRIMARY KEY IDENTITY,
    [ProductPropertyId] INT NOT NULL,
    [BrixMin] FLOAT NOT NULL,
    [BrixMax] FLOAT NOT NULL,
    [BrixAvg] FLOAT NOT NULL,
    [AcidityTypeId] INT NOT NULL,
    [AcidityMin] FLOAT NOT NULL,
    [AcidityMax] FLOAT NOT NULL,
    [AcidityAvg] FLOAT NOT NULL,
    [PhMin] FLOAT NOT NULL,
    [PhMax] FLOAT NOT NULL,
    [PhAvg] FLOAT NOT NULL,
    [isPuree] BIT NOT NULL,
    [isCloudy] BIT NOT NULL,
    [HunterLMin] FLOAT NULL,
    [HunterLMax] FLOAT NULL,
    [HunterLAvg] FLOAT NULL,
    [HunerAMin] FLOAT NULL,
    [HunterAMax] FLOAT NULL,
    [HunterAAvg] FLOAT NULL,
    [HunterBMin] FLOAT NULL,
    [HunterBMax] FLOAT NULL,
    [HunterBAvg] FLOAT NULL,
    [isRedClear] BIT NOT NULL,
    [Abs520Min] FLOAT NULL,
    [Abs520Max] FLOAT NULL,
    [Abs520Avg] FLOAT NULL,
    [Abs430Min] FLOAT NULL,
    [Abs430Max] FLOAT NULL,
    [Abs430Avg] FLOAT NULL,
    [ColorRatio] FLOAT NULL,
    [isLightClear] BIT NOT NULL,
    [Trans440Min] FLOAT NULL,
    [Trans440Max] FLOAT NULL,
    [Trans440Avg] FLOAT NULL,
    [Trans625Min] FLOAT NULL,
    [Trans625Max] FLOAT NULL,
    [Trans625Avg] FLOAT NULL,
    [DateCreated] DATETIME NOT NULL,
    [UserCreated] INT NOT NULL,
    [DateUpdated] DATETIME NOT NULL,
    [UserUpdated] INT NOT NULL,
    [DateDeleted] DATETIME NULL,
    [UserDeleted] INT NULL,
    [isDeleted] BIT NOT NULL,
    CONSTRAINT [FK_ProductQuality_AcidityType] FOREIGN KEY ([AcidityTypeId]) REFERENCES [AcidityType]([AcidityTypeId]),


)
